# Cloudflare Pages configuration
name = "casais-na-rocha"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
publish = "dist"

[env.production]
# Add any environment variables here if needed

[env.preview]
# Preview environment settings